<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
		'Create' => 'Erstellen',
                'Update' => 'Bearbeiten',
                'View' => 'Ansicht',
                'Print View' => 'Druck Ansicht',
                'Export actions' => 'Export aktionen',
                'File operations' => 'Datei operationen',
                'Files' => 'Dateien',
                'Filesystem' => 'Dateisystem',
                'Fileexplorer' =>'Dateiexplorer',
                'List files' => 'Datei Liste',
                'Create dir' => 'Verz. erstellen',
                'Upload files' => 'Dateien hochladen',
                'Advanced search' => 'Erweiterte Suche',
                'Bookmark' => 'Lesezeichen',
                'privat'=>'Privat',
                'my usergroups'=>'Meine Benutzergruppen',
                'public'=>'öffentlich',
		'selected usergroup'=>'Ausgew. Benutzergr.',
                'available'=>'verfügbar',
                'upload'=>'hochladen',
                'Path'=>'Pfad',
                'Make dir'=>'Verzeichniss erstellen',
                'Template'=>'Vorlage',
                'Directory'=>'Verzeichnis',
                'size'=>'Größe',
                'modified'=>'Änderungsdatum',
                'mimeType'=>'Dateiart',
                'permissions'=>'Rechte',
                'owners'=>'Besitzer',
                'move'=>'verschieben',
                'delete'=>'löschen',
                'copy'=>'kopieren',
                'download'=>'herunterladen',
                'paste'=>'einfügen',
                'rename'=>'umbenennen',
                'successfully'=>'erfolgreich',
                'not successfully'=>'nicht erfolgreich',
                'minetype not allowed'=>'Datei Typ nicht erlaupt',
                'error'=>'fehler',
                'warning'=>'Achtung',
                '{file} was successfully created'=>'{file} wurde erfolgreich erstellt',
                '{file} was successfully copied'=>'{file} wurde erfolgreich kopiert',
                '{file} was successfully moved'=>'{file} wurde erfolgreich verschoben',
                '{file} was successfully renamed'=>'{file} wurde erfolgreich umbenannt',
                '{file} was successfully deleted'=>'{file} wurde erfolgreich gelöscht',
                '{file} was successfully change owners'=>'{file} wurden erfolgreich die Eigentümer geändert',
                '{file} was successfully change permissions'=>'{file} wurden erfolgreich die Zugriffsrechte geändert',
                'not created'=>'nicht erfolgreich erstellt',
                'create file or directory'=>'Datei oder Verzeichniss erstellen',
                'please select the target dir on treeview' => 'Bitte Ziel Verz., rechts in Ansicht ausw.  ',
                'new' => 'Neu',
                'files was copy in memory'=>'Dateien in die zwischenablage eingefügt',
                'open dir' => 'Verz. geöffnet',
                'open successfully' => 'öffnen erfolgreich',
                'open not successfully' => 'öffnen nicht erfolgreich',
                'save changed file not successfully'=> 'geänderte Datei speichern nicht erfolgreich',
                'save changed file successfully'=> 'geänderte Datei speichern erfolgreich',
                'goto parent dir' => 'Verz. Ebene höher'
					);
?>