<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Create' => 'Anlegen',
  'Delete' => 'Löschen',
  'Destination' => 'Ziel',
  'File to delete' => 'Zu löschende Datei',
  'Item: ' => 'Objekt: ',
  'Move' => 'Verschieben',
  'New Directory' => 'Neues Verzeichnis',
  'New Name' => 'Neuer Name',
  'Rename' => 'Umbenennen',
  'Upload' => 'Hochladen',
  'Action' => 'Aktion',
  'Base Path' => 'Basis-Pfad',
  'Confirm to delete this item:' => 'Bestätigen Sie das Löschen dieses Objekts:',
  'Copy directory {dir}' => 'Verzeichnis {dir} kopieren',
  'Copy file {file}' => 'Datei {dir} kopieren',
  'Create New Dir' => 'Neues Verzeichnis anlegen',
  'Date' => 'Datum',
  'Delete directory {dir}' => 'Verzeichnis {dir} löschen',
  'Delete file {file}' => 'Datei {file} löschen',
  'Directory' => 'Verzeichnis',
  'Enter the name for the new directory:' => 'Geben Sie den Namen für das neue Verzeichnis ein:',
  'Enter the new location:' => 'Geben Sie den neuen Ort ein:',
  'Enter the new destination and name:' => 'Geben Sie den neuen Ort und Namen ein:',
  'Enter the new name:' => 'Geben Sie den neuen Namen ein:',
  'Icon' => 'Icon',
  'IconCopy' => 'C',
  'IconDelete' => 'X',
  'IconMove' => 'V',
  'IconRename' => 'U',
  'Media Browser' => 'Media-Browser',
  'Media Type' => 'Medien-Typ',
  'Move directory {dir}' => 'Verzeichnis {dir} verschieben',
  'Move file {file} to another location' => 'Datei {file} an einen anderen Ort verschieben',
  'Name' => 'Name',
  'Old Name' => 'Bisheriger Name',
  'Parameter 1' => 'Parameter 1',
  'Path' => 'Pfad',
  'Rename directory {dir}' => 'Verzeichnis {dir} umbenennen',
  'Rename file {file}' => 'Datei {file} umbenennen',
  'Select a file to be uploaded:' => 'Wählen Sie eine Datei zum Hochladen aus:',
  'Size' => 'Größe',
  'The directory <em>{p1}</em> has been created.' => 'Das Verzeichnis <em>{p1}</em> wurde angelegt.',
  'The file <em>{oldName}</em> has been uploaded as <em>{name}</em>.' => 'Die Datei <em>{oldName}</em> wurde hochgeladen als <em>{name}</em>.',
  'The {mediaType} <em>{name}</em> has been deleted.' => '{mediaType} <em>{name}</em> wurde gelöscht.',
  'The {mediaType} <em>{name}</em> has been moved to <em>{path}/{p1}</em>.' => '{mediaType} <em>{name}</em> wurde verschoben nach <em>{path}/{p1}</em>.',
  'The {mediaType} <em>{name}</em> has been renamed to <em>{p1}</em>.' => '{mediaType} <em>{name}</em> wurde umbenannt nach <em>{p1}</em>.',
  'Type' => 'Typ',
  'Upload File' => 'Datei hochladen',
  'directory' => 'Verzeichnis',
  'file' => 'Datei',
   'Filemanager' => 'Dateiverwaltung', 
  'Manage Files and Docs' => 'Verwalte Dokumente und Datei Anhänge'  
);
