<?php

/**
 * This is the model base class for the table "county".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "County".
 *
 * Columns in table "county" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $state_id
 * @property string $name
 *
 */
abstract class BaseCounty extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'county';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'County|Counties', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('state_id, name', 'required'),
			array('state_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>200),
			array('id, state_id, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
	
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'state_id' => Yii::t('app', 'State'),
			'name' => Yii::t('app', 'Name'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}