<?php

/**
 * This is the model base class for the table "city".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "City".
 *
 * Columns in table "city" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $state_id
 * @property integer $county_id
 * @property string $name
 * @property double $lat
 * @property double $lng
 *
 */
abstract class BaseCity extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'city';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'City|Cities', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('state_id, county_id, name, lat, lng', 'required'),
			array('state_id, county_id', 'numerical', 'integerOnly'=>true),
			array('lat, lng', 'numerical'),
			array('name', 'length', 'max'=>200),
			array('id, state_id, county_id, name, lat, lng', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'state_id' => Yii::t('app', 'State'),
			'county_id' => Yii::t('app', 'County'),
			'name' => Yii::t('app', 'Name'),
			'lat' => Yii::t('app', 'Lat'),
			'lng' => Yii::t('app', 'Lng'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('county_id', $this->county_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('lat', $this->lat);
		$criteria->compare('lng', $this->lng);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}