<?php

/**
 * This is the model base class for the table "zipcode".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Zipcode".
 *
 * Columns in table "zipcode" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $city_id
 * @property integer $district_id
 * @property string $zipcode
 *
 */
abstract class BaseZipcode extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'zipcode';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Zipcode|Zipcodes', $n);
	}

	public static function representingColumn() {
		return 'zipcode';
	}

	public function rules() {
		return array(
			array('city_id, zipcode', 'required'),
			array('city_id, district_id', 'numerical', 'integerOnly'=>true),
			array('zipcode', 'length', 'max'=>10),
			array('district_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, city_id, district_id, zipcode', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'city_id' => Yii::t('app', 'City'),
			'district_id' => Yii::t('app', 'District'),
			'zipcode' => Yii::t('app', 'Zipcode'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('city_id', $this->city_id);
		$criteria->compare('district_id', $this->district_id);
		$criteria->compare('zipcode', $this->zipcode, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}