<?php

/**
 * This is the model base class for the table "district".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "District".
 *
 * Columns in table "district" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $city_id
 * @property string $name
 * @property double $lat
 * @property double $lng
 *
 */
abstract class BaseDistrict extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'district';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'District|Districts', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('city_id, name, lat, lng', 'required'),
			array('city_id', 'numerical', 'integerOnly'=>true),
			array('lat, lng', 'numerical'),
			array('name', 'length', 'max'=>200),
			array('id, city_id, name, lat, lng', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'city_id' => Yii::t('app', 'City'),
			'name' => Yii::t('app', 'Name'),
			'lat' => Yii::t('app', 'Lat'),
			'lng' => Yii::t('app', 'Lng'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('city_id', $this->city_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('lat', $this->lat);
		$criteria->compare('lng', $this->lng);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}